name: Clang Format Check

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for non-ASCII characters
        run: |
          NON_ASCII=$(grep -P -n "[^\x00-\x7F]" $(find . -type f \( -name "*.cpp" -o -name "*.hpp" -o -name "*.cc" -o -name "*.c" -o -name "*.h" \)) || true)
          if [[ -n "$NON_ASCII" ]]; then
            echo "❌ Non-ASCII characters detected in source files:"
            echo "$NON_ASCII"
            exit 1
          else
            echo "✅ No non-ASCII characters found."
          fi   

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          FILES=$(find . -regex '.*\.\(cpp\|hpp\|cc\|c\|h\)' -not -path "./build/*")
          clang-format -i $FILES

      - name: Check for formatting issues
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "❌ Formatting issues found. Please run clang-format locally." >&2
            git diff
            exit 1
          else
            echo "✅ All files are properly formatted."
          fi 
      
